# ████████╗███╗   ███╗██╗   ██╗██╗  ██╗
# ╚══██╔══╝████╗ ████║██║   ██║╚██╗██╔╝
#    ██║   ██╔████╔██║██║   ██║ ╚███╔╝
#    ██║   ██║╚██╔╝██║██║   ██║ ██╔██╗
#    ██║   ██║ ╚═╝ ██║╚██████╔╝██╔╝ ██╗
#    ╚═╝   ╚═╝     ╚═╝ ╚═════╝ ╚═╝  ╚═╝
# Terminal multiplexer
# https://github.com/tmux/tmux

# TODO: learn how this works
set-option -g focus-events on

# TODO: find a way to toggle this?
set-option -g display-time 3000

# FIX: user action isn't recognized by Wezterm via `run-shell` 😭
# set-hook -g client-session-changed 'run-shell -t :1 "tmux-session-changed"'
bind J resize-pane -D 20
bind K resize-pane -U 20
bind L resize-pane -L 20
bind H resize-pane -R 20
bind-key -n C-k  select-pane -U
bind-key -n C-j  select-pane -D
bind-key -n C-l  select-pane -L
bind-key -n C-h  select-pane -R
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# colors
set -g default-terminal "tmux-256color"
set-option -a terminal-features 'xterm-256color:RGB'
# set -ga update-environment TERM
# set -ga update-environment TERM_PROGRAM
# set -g default-terminal "${TERM}"

set-option -g automatic-rename on
set-option -g automatic-rename-format '#{pane_current_command}'

set -g base-index 1          # start indexing windows at 1 instead of 0
set -g detach-on-destroy off # don't exit from tmux when closing a session
set -g escape-time 0         # zero-out escape time delay
set -g history-limit 1000000 # increase history size (from 2,000)
set -g mouse on              # enable mouse support
set -g renumber-windows on   # renumber all windows when any window is closed
set -g set-clipboard on      # use system clipboard
set -g status-interval 3     # update the status bar every 3 seconds

set -g status-left ""
set -g status-left-length 200    # increase length (from 10)
set -g status-right-length 200   # increase length (from 10)
set -g status-position bottom      # macOS / darwin style
set -g status-style 'bg=default' # transparent


# Set right side status bar length and style
set -g status-right-length 140
set -g status-right-style default

# Display the cpu load (Mac OS)
set -g status-interval 2
# set -g status-right "#[fg=green,bg=default,bright]  #($TMUX_PLUGIN_MANAGER_PATH/tmux-mem-cpu-load/tmux-mem-cpu-load --colors --powerline-right --interval 2)#[default]"
set -g status-right '#[fg=white] 󰍛 #($TMUX_PLUGIN_MANAGER_PATH/tmux-mem-cpu-load/tmux-mem-cpu-load -t % -l 52 -r 33 -g 0 -a 2 --interval 2)#[default]'
# Display the date
set -ag status-right "#[fg=white,bg=default]   %a %d #[default]"
# Display the time
set -ag status-right "#[fg=#ebbcba,bright,bg=default] 󰥔 %l:%M %p #[default]"
# Display the hostname
set -ag status-right "#[fg=cyan,bg=default] ☠ #H #[default]"

set -g window-status-current-format '#[fg=magenta]#W'
set -g window-status-format '#[fg=#353535]#W'

set -g allow-passthrough on
set -g message-command-style bg=default,fg=yellow
set -g message-style bg=default,fg=yellow
set -g mode-style bg=default,fg=yellow
set -g pane-active-border-style 'fg=white,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'

# community plugins
set -g @plugin 'fcsonline/tmux-thumbs'          
set -g @plugin 'rickstaa/tmux-notify'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'thewtex/tmux-mem-cpu-load'

set -g @plugin 'tmux-plugins/tpm'        # load tpm
run "$HOME/.tmux/plugins/tpm/tpm" # run tpm (always end of file)
bind r source-file ~/.tmux.conf
